###############################################################################
#
# Monitoring-Grafana Project
#
# File:
#   configs/traefik/dynamic/crowdsec.yml
#
# Description:
#   CrowdSec middleware.
#
###############################################################################

http:

  ###########################################################################
  # Middlewares
  ###########################################################################

  middlewares:

    #########################################################################
    # CrowdSec
    #########################################################################

    crowdsec:

      plugin:

        crowdsec:

          enabled: true

          crowdsecMode: live

          crowdsecLapiScheme: http

          crowdsecLapiHost: crowdsec:8080

          crowdsecLapiKeyFile: /etc/traefik/crowdsec/BOUNCER_KEY_traefik

          forwardedHeadersTrustedIPs:

            - 127.0.0.1/32

            - 10.0.0.0/8

            - 172.16.0.0/12

            - 192.168.0.0/16