###############################################################################
#
# Monitoring-Grafana Project
#
###############################################################################

http:

  middlewares:

    ip-whitelist:

      ipAllowList:

        sourceRange:

          - "10.100.100.0/24"