###############################################################################
#
# Monitoring-Grafana Project
#
# File:
#   configs/traefik/dynamic/metabase.yml
#
# Description:
#   Metabase router and service.
#
###############################################################################

http:

  ###########################################################################
  # Routers
  ###########################################################################

  routers:

    #########################################################################
    # Metabase
    #########################################################################

    metabase:

      entryPoints:

        - metabase

      #
      # Administration URL
      #
      #   https://10.100.100.1:9444/
      #
      # (dedicated port -- no subpath, see traefik.yml)
      #

      rule: PathPrefix(`/`)

      service: metabase

      middlewares:

        - default-chain

      tls:

        options: default

      priority: 1

  ###########################################################################
  # Services
  ###########################################################################

  services:

    #########################################################################
    # Metabase
    #########################################################################

    metabase:

      loadBalancer:

        passHostHeader: true

        servers:

          - url: http://metabase:3000
