###############################################################################
#
# Monitoring-Grafana Project
#
# File:
#   configs/traefik/dynamic/metabase.yml
#
# Description:
#   Metabase router and service.
#
###############################################################################

http:

  ###########################################################################
  # Routers
  ###########################################################################

  routers:

    #########################################################################
    # Metabase
    #########################################################################

    metabase:

      entryPoints:

        - admin

      #
      # Administration URL
      #
      #   https://10.100.100.1:9443/metabase/
      #
      # Internally:
      #
      #   https://10.10.10.10:8443/metabase/
      #

      rule: >
        PathPrefix(`/metabase`) ||
        PathPrefix(`/metabase/`)

      service: metabase

      middlewares:

        - default-chain

      tls:

        options: default

      priority: 100

  ###########################################################################
  # Services
  ###########################################################################

  services:

    #########################################################################
    # Metabase
    #########################################################################

    metabase:

      loadBalancer:

        passHostHeader: true

        servers:

          - url: http://metabase:3000