###############################################################################
#
# Monitoring-Grafana Project
#
# File:
#   configs/traefik/dynamic/vault.yml
#
# Description:
#   Central Traefik route to HashiCorp Vault running in a
#   separate Incus container.
#
# Backend:
#
#   Vault Incus container
#   IP: 10.10.10.11
#   Port: 8200
#
# Public hostname:
#
#   vault.serveftp.org
#
###############################################################################

http:

  ###########################################################################
  # Router
  ###########################################################################

  routers:

    vault:

      entryPoints:
        - websecure

      rule: "Host(`vault.serveftp.org`)"

      service: vault

      tls:
        certResolver: letsencrypt


  ###########################################################################
  # Service
  ###########################################################################

  services:

    vault:

      loadBalancer:

        passHostHeader: true

        servers:

          - url: "http://10.10.10.11:8200"