###############################################################################
#
# CrowdSec profiles
#
###############################################################################

name: default_ip_remediation

filters:
  - Alert.Remediation == true

decisions:
  - type: ban
    duration: 4h

on_success: break