#!/usr/bin/env bash

###############################################################################
#
# Monitoring-Grafana
#
# SNMP Exporter Builder v2.0
#
###############################################################################

set -Eeuo pipefail

VERSION="2.0"

###############################################################################
# Paths
###############################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

MODULE_DIR="${SCRIPT_DIR}/modules"

OUTPUT_FILE="${SCRIPT_DIR}/snmp.yml"

BACKUP_FILE="${SCRIPT_DIR}/snmp.yml.bak"

###############################################################################
# Options
###############################################################################

CHECK_ONLY=false
VERBOSE=false
RESTART=false

###############################################################################
# Colors
###############################################################################

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

###############################################################################
# Functions
###############################################################################

info() {

    echo -e "${BLUE}==>${NC} $1"

}

ok() {

    echo -e "${GREEN}✔${NC} $1"

}

warn() {

    echo -e "${YELLOW}⚠${NC} $1"

}

fail() {

    echo -e "${RED}✖${NC} $1"

    exit 1

}

usage() {

cat <<EOF

Monitoring-Grafana

SNMP Exporter Builder ${VERSION}

Použití

    ./build-snmp.sh

Volby

    --check

        pouze kontrola konfigurace

    --restart

        restart snmp-exporter po úspěšném buildu

    --verbose

        podrobný výpis

    --help

        tato nápověda

EOF

exit 0

}

###############################################################################
# Parse arguments
###############################################################################

while [[ $# -gt 0 ]]
do

    case "$1" in

        --check)

            CHECK_ONLY=true

            ;;

        --restart)

            RESTART=true

            ;;

        --verbose)

            VERBOSE=true

            ;;

        --help|-h)

            usage

            ;;

        *)

            fail "Neznámý parametr: $1"

            ;;

    esac

    shift

done

###############################################################################
# Checks
###############################################################################

[[ -d "${MODULE_DIR}" ]] || fail "Adresář modules neexistuje."

###############################################################################
# Banner
###############################################################################

echo

echo "============================================================"

echo " Monitoring-Grafana"

echo " SNMP Exporter Builder ${VERSION}"

echo "============================================================"

echo

###############################################################################
# Scan modules
###############################################################################

info "Kontrola modulů"

COUNT=0

declare -A MODULE_NAMES

for file in "${MODULE_DIR}"/*.yml
do

    [[ -f "$file" ]] || continue

    [[ -s "$file" ]] || fail "$(basename "$file") je prázdný."

    name=$(grep '^  [a-zA-Z0-9_-]\+:' "$file" | head -1 | sed 's/://')

    if [[ -n "$name" ]]
    then

        if [[ -n "${MODULE_NAMES[$name]:-}" ]]
        then

            fail "Duplicitní modul: ${name}"

        fi

        MODULE_NAMES[$name]=1

    fi

    ((COUNT++))

    if $VERBOSE
    then

        ok "$(basename "$file")"

    fi

done

[[ "$COUNT" -gt 0 ]] || fail "Nenalezen žádný modul."

ok "Počet modulů: ${COUNT}"

###############################################################################
# Check only
###############################################################################

if $CHECK_ONLY
then

    ok "Kontrola dokončena."

    exit 0

fi

###############################################################################
# Backup
###############################################################################

if [[ -f "$OUTPUT_FILE" ]]
then

    cp "$OUTPUT_FILE" "$BACKUP_FILE"

    ok "Vytvořena záloha snmp.yml"

fi

###############################################################################
# Build
###############################################################################

info "Generuji snmp.yml"

cat > "$OUTPUT_FILE" <<EOF
###############################################################################
#
# AUTO GENERATED FILE
#
# Generated by build-snmp.sh
#
# DO NOT EDIT
#
###############################################################################

EOF

for file in "${MODULE_DIR}"/*.yml
do

    echo >> "$OUTPUT_FILE"

    echo "# ------------------------------------------------------------------" >> "$OUTPUT_FILE"

    echo "# $(basename "$file")" >> "$OUTPUT_FILE"

    echo "# ------------------------------------------------------------------" >> "$OUTPUT_FILE"

    cat "$file" >> "$OUTPUT_FILE"

    echo >> "$OUTPUT_FILE"

done

ok "snmp.yml vytvořen."

###############################################################################
# Restart
###############################################################################

if $RESTART
then

    info "Restartuji snmp-exporter"

    docker compose restart snmp-exporter

fi

###############################################################################
# Done
###############################################################################

echo

ok "Hotovo."

echo