# ==============================================================================
# Cisco Memory
# ==============================================================================
#
# CISCO-MEMORY-POOL-MIB
#
# Modul obsahuje:
#
#   ✔ využití RAM
#
#   ✔ free RAM
#
#   ✔ used RAM
#
# ==============================================================================