# ==============================================================================
# Cisco CPU
# ==============================================================================
#
# CISCO-PROCESS-MIB
#
# Modul obsahuje:
#
#   ✔ CPU 1 min
#
#   ✔ CPU 5 min
#
#   ✔ CPU 15 min
#
# ==============================================================================