# ==============================================================================
# Cisco Power over Ethernet
# ==============================================================================
#
# POWER-ETHERNET-MIB
#
# Modul obsahuje:
#
#   ✔ Celkový PoE budget
#
#   ✔ Aktuální spotřebu
#
#   ✔ Volný výkon
#
#   ✔ Stav PoE portů
#
#   ✔ Prioritu portů
#
#   ✔ Detekci PD
#
#   ✔ Spotřebu jednotlivých portů
#
# Testováno:
#
#   Catalyst 3560
#
# ==============================================================================