# ==============================================================================
# MikroTik
# ==============================================================================
#
# Obsahuje:
#
#   • RouterOS
#   • CRS
#   • CSS
#
# Použité MIB:
#
#   IF-MIB
#   IF-X-MIB
#   HOST-RESOURCES-MIB
#   MIKROTIK-MIB
#
# Nepřidávej sem Cisco OID.
#
# ==============================================================================